version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-container
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD: 'Passw0rd'
      - ACCEPT_EULA: 'Y'