version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch-apm
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.0
    container_name: server-apm
    depends_on:
      - elasticsearch
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana-apm
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
