version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins-container
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: jenkins-data
volumes:
  jenkins-data: