version: '3'

services:
  jenkins:
    image: portainer/portainer
    container_name: portainer-container
    ports:
      - 9000:9000
    restart: always
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer-data: