version: '3'

services:
  influxdb:
    image: influxdb
    container_name: influxdb-container
    ports:
      - 8086:8086
      - 2003:2003
      - 25826:25826/udp
    networks:
      - influxdbnet
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=testing
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
      - INFLUXDB_READ_USER=user_read
      - INFLUXDB_READ_USER_PASSWORD=user_read
      - INFLUXDB_WRITE_USER=user_write
      - INFLUXDB_WRITE_USER_PASSWORD=user_write
    volumes:
      - influxdb_data:/var/lib/influxdb
  chronograf:
    image: chronograf
    container_name: chronograf-container
    ports:
      - 8888:8888
    networks:
      - influxdbnet
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb

networks:
  influxdbnet:
    driver: bridge

volumes:
  influxdb_data:
  chronograf_data: