version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-develop
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    restart: always
    ports:
      - 37017:3000
    volumes:
      - mongoclient-data:/data/db

volumes:
  mongoclient-data: