version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-develop
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongonet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --serviceExecutor adaptive

  mongoclient:
    image: mongoclient/mongoclient
    container_name: mongoclient
    restart: always
    ports:
      - 37017:3000
    networks:
      - mongonet
    volumes:
      - mongoclient-data:/data/db
    depends_on:
      - mongo

volumes:
  mongoclient-data:

networks:
  mongonet:
    driver: bridge